before:
  hooks:
    - 'go mod tidy'
    - 'go generate ./...'

builds:
  - main: './cmd/daemon'
    ldflags:
      - '-s -w'
      - '-X go-librespot.commit={{.ShortCommit}}'
      - '-X go-librespot.version={{.Version}}'
    env:
      - 'CGO_ENABLED=1'
    goos:
      - 'linux'
    goarch:
      - 'amd64'
      - 'arm'
      - 'arm64'
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: arm
        goarm: 6
        env:
          - CC=arm-linux-gnueabihf-gcc
      - goos: linux
        goarch: amd64
        goamd64: v1
        env:
          - CC=gcc

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- trim .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
