name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            gcc libasound2-dev libogg-dev libvorbis-dev \
            gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

      - name: Download alsa-lib sources
        working-directory: /tmp
        run: |
          wget http://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.10.tar.bz2
          tar -xvf alsa-lib-1.2.10.tar.bz2

      - name: Cross-compile alsa-lib for armhf
        working-directory: /tmp
        run: |
          cd alsa-lib-1.2.10
          ./configure --enable-shared=yes --enable-static=no --with-pic \
            --host=arm-linux-gnueabihf --prefix=/usr/arm-linux-gnueabihf
          make
          sudo make install
          make clean

      - name: Cross-compile alsa-lib for arm64
        working-directory: /tmp
        run: |
          cd alsa-lib-1.2.10
          ./configure --enable-shared=yes --enable-static=no --with-pic \
            --host=aarch64-linux-gnu --prefix=/usr/aarch64-linux-gnu
          make
          sudo make install
          make clean

      - name: Download libogg sources
        working-directory: /tmp
        run: |
          wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.xz
          tar -xvf libogg-1.3.5.tar.xz

      - name: Cross-compile libogg for armhf
        working-directory: /tmp
        run: |
          cd libogg-1.3.5
          ./configure --host=arm-linux-gnueabihf --prefix=/usr/arm-linux-gnueabihf
          make
          sudo make install
          make clean

      - name: Cross-compile libogg for arm64
        working-directory: /tmp
        run: |
          cd libogg-1.3.5
          ./configure --host=aarch64-linux-gnu --prefix=/usr/aarch64-linux-gnu
          make
          sudo make install
          make clean

      - name: Download libvorbis sources
        working-directory: /tmp
        run: |
          wget https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz
          tar -xvf libvorbis-1.3.7.tar.xz

      - name: Cross-compile libvorbis for armhf
        working-directory: /tmp
        run: |
          cd libvorbis-1.3.7
          ./configure --host=arm-linux-gnueabihf --prefix=/usr/arm-linux-gnueabihf
          make
          sudo make install
          make clean

      - name: Cross-compile libvorbis for arm64
        working-directory: /tmp
        run: |
          cd libvorbis-1.3.7
          ./configure --host=aarch64-linux-gnu --prefix=/usr/aarch64-linux-gnu
          make
          sudo make install
          make clean

      - uses: goreleaser/goreleaser-action@v4
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}